vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        phone_images:
            uri_prefix: /images/phone
            upload_destination: "%kernel.project_dir%/public/images/phone"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true